import PDFDocument from "pdfkit"

export const buildPdf = (docData) =>
    new Promise((resolve, reject) => {
        const doc = new PDFDocument({ 
            size:"A4",
            margin: 50,
            info:{
                Author:"Praxis",
                Title:docData.title,
                Creator:"Praxis pdf agent"
            }
        })
        const chunks = []

        doc.on("data", (chunk) => chunks.push(chunk))
        doc.on("end", () => resolve(Buffer.concat(chunks)))
        doc.on("error", reject)

        // title
        doc.fontSize(24).font("Helvetica-Bold").text(docData.title, { align: "center" })
        doc.moveDown(2)

        // sections
        docData.sections?.forEach((s) => {
            if (s.heading) {
                doc.fontSize(15).font("Helvetica-Bold").text(s.heading)
                doc.moveDown(0.5)
            }
            if (s.content) {
                doc.fontSize(11).font("Helvetica").text(s.content, { align: "justify", lineGap: 4 })
                doc.moveDown(1)
            }
        })

        doc.moveDown(2)

        doc.fontSize(8).font("Helvetica-Bold").fillColor("#b3b8c2").text("Generated by PraxisAI", { align: "center" }).fillColor("#000000")
        doc.moveDown(2)

        doc.end()
    })
