import PptxGenJS from "pptxgenjs"

export const buildPpt = async (pptData) => {
    const pptx = new PptxGenJS()
    pptx.defineLayout({ name: "WIDE", width: 13.33, height: 7.5 })
    pptx.layout = "WIDE"

    const title = pptx.addSlide()
    title.background = { color: "0D0F14" }
    title.addText(pptData.title, { x: 0.8, y: 2.6, w: 11.7, h: 1.2, fontSize: 40, bold: true, color: "E8ECF4", align: "center" })

    if (pptData.subtitle) {
        title.addText(pptData.subtitle, { x: 0.8, y: 3.9, w: 11.7, h: 0.8, fontSize: 18, color: "8B93A7", align: "center" })
    }

    pptData.slides?.forEach((s) => {
        const slide = pptx.addSlide()
        slide.background = { color: "0D0F14" }
        slide.addText(s.heading, { x: 0.6, y: 0.4, w: 12, h: 0.8, fontSize: 26, bold: true, color: "818CF8" })
        slide.addText(
            (s.bullets || []).map((b) => ({ text: b, options: { bullet: true, breakLine: true } })),
            { x: 0.8, y: 1.5, w: 11.7, h: 5.2, fontSize: 16, color: "E8ECF4", lineSpacing: 28 }
        )
        slide.addText("Generated by PraxisAI", { x: 0.6, y: 7.05, w: 12, h: 0.3, fontSize: 9, color: "5A6172", align: "center" })
    })

    return await pptx.write("nodebuffer")
}
